version: "3.9"

services:
  mongo:
    container_name : mongo
    image : mongo:5.0.3
    ports : 
      - 4122:27017      
    networks:
      - shipping_network
    environment :
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=HappySharia123      
    volumes :
      - mongo_shipping:/data/db
  shipping :
    container_name : shipping
    image : 04012002/shipping:1.0
    ports :
      - 9999:3000
    networks:
      - shipping_network
    depends_on :
      - mongo
    environment :
      - MONGO_URL=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=HappySharia123
    
networks :
  shipping_network :
    name : shipping_network

volumes : 
  mongo_shipping :
    external : true